apiVersion: v1
kind: Service
metadata:
  name: selenosis
  namespace: selenosis
spec:
  type: LoadBalancer
  ports:
  - name: selenium
    port: 4444
    protocol: TCP
    targetPort: 4444
    nodePort: 31000
  selector:
    app: selenosis
  sessionAffinity: None


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: selenoid
  namespace: selenosis
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  rules:
  - host: selenosis.test.in
    http:
      paths:
      - backend:
          service:
            name: selenosis
            port:
              number: 4444
        path: /
        pathType: Prefix
---
apiVersion: v1
kind: Service
metadata:
  name: seleniferous
  namespace: selenosis
spec:
  selector:
    type: browser
  clusterIP: None
  publishNotReadyAddresses: true

