apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenoid-ui
  namespace: selenosis
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: selenoid-ui
  template:
    metadata:
      labels:
        app: selenoid-ui
        selenosis.app.type: worker
      namespace: selenosis
    spec:
      containers:
        - args: ["--status-uri", "http://localhost:4444", "-webdriver-uri", "http://selenosis:4444"]
          name: selenoid-ui
          imagePullPolicy: IfNotPresent
          image: aerokube/selenoid-ui:1.10.1
          resources:
            limits:
              cpu: "0.25"
              memory: "64Mi"
            requests:
              cpu: "0.05"
              memory: "64Mi"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
        - args: ["--port", ":4444", "--selenosis-url", "http://selenosis:4444"]
          name: selenoid-ui-adapter
          imagePullPolicy: IfNotPresent
          image: alcounit/adaptee:v0.0.2-develop
          resources:
            limits:
              cpu: "0.25"
              memory: "64Mi"
            requests:
              cpu: "0.05"
              memory: "64Mi" 
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: Service
metadata:
  name: selenoid-ui
  namespace: selenosis
spec:
  type: LoadBalancer
  ports:
    - name: selenoid-ui
      port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 32000
  selector:
    app: selenoid-ui
  sessionAffinity: None

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: selenoid-ui
  namespace: selenosis
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  rules:
  - host: selenosis-ui.test.in
    http:
      paths:
      - backend:
          service:
            name: selenoid-ui
            port: 
              number: 8080
        path: /
        pathType: Prefix
