- request:
    method: GET
    headers:
      content-type: application/json
    url: /item/redirect/source

  response:
    status: 301
    headers:
      location: /item/redirect/destination


- request:
    method: GET
    headers:
      content-type: application/json
    url: /item/redirect/destination

  response:
    headers:
      content-type: application/json
    status: 200
    body: >
      {"response" : "content"}

-  request:
     method: [GET]
     url: /maps/api/geocode/json
     query:
       address: "1600%20Amphitheatre%20Parkway,%20Mountain%20View,%20CA"
       sensor: false

   response:
     status: 200
     headers:
       content-type: application/json
     body: http://maps.googleapis.com